### ISSUE TITLE
redirects with parameters

### ISSUE THREAD

**Issue by DanielleDeman** [ethercreative/seo#47]
redirect with parameters in de url don't work
for example blabla.com/redirectme?par=1 goes to a 404 and blabla.com/redirectme goed to a page

**Comment by DanielleDeman** [comment]
Fixed it my adding $path = strtok($path, '?'); to public function findRedirectByPath ($path)

**Comment by DanielleDeman** [comment]
Would you like me to fork the project and push the solution

**Comment by Tam** [comment]
Yeah that'd be great, thanks!

**Comment by Tam** [comment]
Merged in latest release!

**Comment by jamealg** [comment]
I'm encountering this issue still on the latest Craft 2 release. At least if this is the use case:

1. Set up a redirect from /abc to /xyz
2. Navigate to /abc?ctm_tracking_code=9929292929
3. 404  (expected to go to /xyz)

I was able to fix it by adding some code to `Seo_RedirectService.php`

			$qs = array();
			preg_match('/\?.*/', $path, $qs);
			$path = preg_replace('/\?.*/', '', $path);

			if (trim($redirect['uri'], '/') == $path)
			{
				$to = (count($qs)>0) ? $redirect['to'] . $qs[0] : $redirect['to'];
			}

Not the most elegant but it works. I'm on an older version than the latest Craft 2 release so the code may not be exactly the same but I did confirm the issue on the latest as well.
